// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// clusterLockStore is an autogenerated mock type for the clusterLockStore type
type clusterLockStore struct {
	mock.Mock
}

// LockCluster provides a mock function with given fields: clusterID, lockerID
func (_m *clusterLockStore) LockCluster(clusterID string, lockerID string) (bool, error) {
	ret := _m.Called(clusterID, lockerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(clusterID, lockerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clusterID, lockerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlockCluster provides a mock function with given fields: clusterID, lockerID, force
func (_m *clusterLockStore) UnlockCluster(clusterID string, lockerID string, force bool) (bool, error) {
	ret := _m.Called(clusterID, lockerID, force)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, bool) bool); ok {
		r0 = rf(clusterID, lockerID, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(clusterID, lockerID, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
