// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// installationLockStore is an autogenerated mock type for the installationLockStore type
type installationLockStore struct {
	mock.Mock
}

// LockInstallation provides a mock function with given fields: installationID, lockerID
func (_m *installationLockStore) LockInstallation(installationID string, lockerID string) (bool, error) {
	ret := _m.Called(installationID, lockerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(installationID, lockerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(installationID, lockerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlockInstallation provides a mock function with given fields: installationID, lockerID, force
func (_m *installationLockStore) UnlockInstallation(installationID string, lockerID string, force bool) (bool, error) {
	ret := _m.Called(installationID, lockerID, force)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, bool) bool); ok {
		r0 = rf(installationID, lockerID, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(installationID, lockerID, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
