// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/mattermost/mattermost-cloud/model"
	mock "github.com/stretchr/testify/mock"
)

// installationStore is an autogenerated mock type for the installationStore type
type installationStore struct {
	mock.Mock
}

// CreateClusterInstallation provides a mock function with given fields: clusterInstallation
func (_m *installationStore) CreateClusterInstallation(clusterInstallation *model.ClusterInstallation) error {
	ret := _m.Called(clusterInstallation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ClusterInstallation) error); ok {
		r0 = rf(clusterInstallation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInstallation provides a mock function with given fields: installationID
func (_m *installationStore) DeleteInstallation(installationID string) error {
	ret := _m.Called(installationID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(installationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCluster provides a mock function with given fields: id
func (_m *installationStore) GetCluster(id string) (*model.Cluster, error) {
	ret := _m.Called(id)

	var r0 *model.Cluster
	if rf, ok := ret.Get(0).(func(string) *model.Cluster); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Cluster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusterInstallation provides a mock function with given fields: clusterInstallationID
func (_m *installationStore) GetClusterInstallation(clusterInstallationID string) (*model.ClusterInstallation, error) {
	ret := _m.Called(clusterInstallationID)

	var r0 *model.ClusterInstallation
	if rf, ok := ret.Get(0).(func(string) *model.ClusterInstallation); ok {
		r0 = rf(clusterInstallationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ClusterInstallation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(clusterInstallationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusterInstallations provides a mock function with given fields: _a0
func (_m *installationStore) GetClusterInstallations(_a0 *model.ClusterInstallationFilter) ([]*model.ClusterInstallation, error) {
	ret := _m.Called(_a0)

	var r0 []*model.ClusterInstallation
	if rf, ok := ret.Get(0).(func(*model.ClusterInstallationFilter) []*model.ClusterInstallation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.ClusterInstallation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ClusterInstallationFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusters provides a mock function with given fields: clusterFilter
func (_m *installationStore) GetClusters(clusterFilter *model.ClusterFilter) ([]*model.Cluster, error) {
	ret := _m.Called(clusterFilter)

	var r0 []*model.Cluster
	if rf, ok := ret.Get(0).(func(*model.ClusterFilter) []*model.Cluster); ok {
		r0 = rf(clusterFilter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Cluster)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ClusterFilter) error); ok {
		r1 = rf(clusterFilter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInstallation provides a mock function with given fields: installationID
func (_m *installationStore) GetInstallation(installationID string) (*model.Installation, error) {
	ret := _m.Called(installationID)

	var r0 *model.Installation
	if rf, ok := ret.Get(0).(func(string) *model.Installation); ok {
		r0 = rf(installationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Installation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(installationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnlockedInstallationsPendingWork provides a mock function with given fields:
func (_m *installationStore) GetUnlockedInstallationsPendingWork() ([]*model.Installation, error) {
	ret := _m.Called()

	var r0 []*model.Installation
	if rf, ok := ret.Get(0).(func() []*model.Installation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Installation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWebhooks provides a mock function with given fields: filter
func (_m *installationStore) GetWebhooks(filter *model.WebhookFilter) ([]*model.Webhook, error) {
	ret := _m.Called(filter)

	var r0 []*model.Webhook
	if rf, ok := ret.Get(0).(func(*model.WebhookFilter) []*model.Webhook); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Webhook)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.WebhookFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockCluster provides a mock function with given fields: clusterID, lockerID
func (_m *installationStore) LockCluster(clusterID string, lockerID string) (bool, error) {
	ret := _m.Called(clusterID, lockerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(clusterID, lockerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(clusterID, lockerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockClusterInstallations provides a mock function with given fields: clusterInstallationID, lockerID
func (_m *installationStore) LockClusterInstallations(clusterInstallationID []string, lockerID string) (bool, error) {
	ret := _m.Called(clusterInstallationID, lockerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]string, string) bool); ok {
		r0 = rf(clusterInstallationID, lockerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = rf(clusterInstallationID, lockerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockInstallation provides a mock function with given fields: installationID, lockerID
func (_m *installationStore) LockInstallation(installationID string, lockerID string) (bool, error) {
	ret := _m.Called(installationID, lockerID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(installationID, lockerID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(installationID, lockerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlockCluster provides a mock function with given fields: clusterID, lockerID, force
func (_m *installationStore) UnlockCluster(clusterID string, lockerID string, force bool) (bool, error) {
	ret := _m.Called(clusterID, lockerID, force)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, bool) bool); ok {
		r0 = rf(clusterID, lockerID, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(clusterID, lockerID, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlockClusterInstallations provides a mock function with given fields: clusterInstallationID, lockerID, force
func (_m *installationStore) UnlockClusterInstallations(clusterInstallationID []string, lockerID string, force bool) (bool, error) {
	ret := _m.Called(clusterInstallationID, lockerID, force)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]string, string, bool) bool); ok {
		r0 = rf(clusterInstallationID, lockerID, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, string, bool) error); ok {
		r1 = rf(clusterInstallationID, lockerID, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnlockInstallation provides a mock function with given fields: installationID, lockerID, force
func (_m *installationStore) UnlockInstallation(installationID string, lockerID string, force bool) (bool, error) {
	ret := _m.Called(installationID, lockerID, force)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, bool) bool); ok {
		r0 = rf(installationID, lockerID, force)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, bool) error); ok {
		r1 = rf(installationID, lockerID, force)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClusterInstallation provides a mock function with given fields: clusterInstallation
func (_m *installationStore) UpdateClusterInstallation(clusterInstallation *model.ClusterInstallation) error {
	ret := _m.Called(clusterInstallation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ClusterInstallation) error); ok {
		r0 = rf(clusterInstallation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateInstallation provides a mock function with given fields: installation
func (_m *installationStore) UpdateInstallation(installation *model.Installation) error {
	ret := _m.Called(installation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Installation) error); ok {
		r0 = rf(installation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
