// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	k8s "github.com/mattermost/mattermost-cloud/internal/tools/k8s"
	mock "github.com/stretchr/testify/mock"

	model "github.com/mattermost/mattermost-cloud/model"

	v1alpha1 "github.com/mattermost/mattermost-operator/pkg/apis/mattermost/v1alpha1"
)

// installationProvisioner is an autogenerated mock type for the installationProvisioner type
type installationProvisioner struct {
	mock.Mock
}

// CreateClusterInstallation provides a mock function with given fields: cluster, installation, clusterInstallation
func (_m *installationProvisioner) CreateClusterInstallation(cluster *model.Cluster, installation *model.Installation, clusterInstallation *model.ClusterInstallation) error {
	ret := _m.Called(cluster, installation, clusterInstallation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Cluster, *model.Installation, *model.ClusterInstallation) error); ok {
		r0 = rf(cluster, installation, clusterInstallation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteClusterInstallation provides a mock function with given fields: cluster, installation, clusterInstallation
func (_m *installationProvisioner) DeleteClusterInstallation(cluster *model.Cluster, installation *model.Installation, clusterInstallation *model.ClusterInstallation) error {
	ret := _m.Called(cluster, installation, clusterInstallation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Cluster, *model.Installation, *model.ClusterInstallation) error); ok {
		r0 = rf(cluster, installation, clusterInstallation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetClusterInstallationResource provides a mock function with given fields: cluster, installation, clusterInstallation
func (_m *installationProvisioner) GetClusterInstallationResource(cluster *model.Cluster, installation *model.Installation, clusterInstallation *model.ClusterInstallation) (*v1alpha1.ClusterInstallation, error) {
	ret := _m.Called(cluster, installation, clusterInstallation)

	var r0 *v1alpha1.ClusterInstallation
	if rf, ok := ret.Get(0).(func(*model.Cluster, *model.Installation, *model.ClusterInstallation) *v1alpha1.ClusterInstallation); ok {
		r0 = rf(cluster, installation, clusterInstallation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterInstallation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Cluster, *model.Installation, *model.ClusterInstallation) error); ok {
		r1 = rf(cluster, installation, clusterInstallation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClusterResources provides a mock function with given fields: cluster, onlySchedulable
func (_m *installationProvisioner) GetClusterResources(cluster *model.Cluster, onlySchedulable bool) (*k8s.ClusterResources, error) {
	ret := _m.Called(cluster, onlySchedulable)

	var r0 *k8s.ClusterResources
	if rf, ok := ret.Get(0).(func(*model.Cluster, bool) *k8s.ClusterResources); ok {
		r0 = rf(cluster, onlySchedulable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*k8s.ClusterResources)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Cluster, bool) error); ok {
		r1 = rf(cluster, onlySchedulable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateClusterInstallation provides a mock function with given fields: cluster, installation, clusterInstallation
func (_m *installationProvisioner) UpdateClusterInstallation(cluster *model.Cluster, installation *model.Installation, clusterInstallation *model.ClusterInstallation) error {
	ret := _m.Called(cluster, installation, clusterInstallation)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Cluster, *model.Installation, *model.ClusterInstallation) error); ok {
		r0 = rf(cluster, installation, clusterInstallation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
