// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/mattermost/mattermost-cloud/model"
	mock "github.com/stretchr/testify/mock"
)

// webhookStore is an autogenerated mock type for the webhookStore type
type webhookStore struct {
	mock.Mock
}

// GetWebhooks provides a mock function with given fields: filter
func (_m *webhookStore) GetWebhooks(filter *model.WebhookFilter) ([]*model.Webhook, error) {
	ret := _m.Called(filter)

	var r0 []*model.Webhook
	if rf, ok := ret.Get(0).(func(*model.WebhookFilter) []*model.Webhook); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Webhook)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.WebhookFilter) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
